title: Stephen Gowen
logo: 	https://avatars.githubusercontent.com/u/4435453?s=400&u=58b7fed8dfbd0ec4afd19e6cee12dea3886817b4&v=4
description: Game Developer / Software Engineer / C# Developer
show_downloads: true
theme: jekyll-theme-minimal
